### ISSUE TITLE
RblParse error

### ISSUE THREAD

**Issue by cryptobiotic** [eguidotti/RblDataLicense#2]
Trying the simple example, can see the req file uploaded.   When I try to run RblParse the following error is returned.   "Error in if (programname == "gethistory") { : argument is of length zero"

Tried several different permutations of the example request, diff days, diff securities.  I have a valid data license account that is used regularly as well.

**Comment by eguidotti** [comment]
It seems you are trying to parse the wrong file or the request was malformed. To check you can:
- upload the ".req" file
- wait for the corresponding ".out" or ".out.gz" file to be generated by Bloomberg
- download the ".out" or ".out.gz" file with the `RblDownload` function
- check the output of the `RblDownload` function: this is the path to the local copy of the file. Then browse for the local file path and open the file with a text editor. Is this the right file to import into R?

Another option would be trying to run directly the `RblQuery` example. This should work out-of-the box. If it doesn't, please share more details so we can investigate the issue further. 

Did this solve the problem?

**Comment by cryptobiotic** [comment]
Thank you.   Followed all of those steps exactly.  Looking at the *.out.gz file, it seems to be scrambled:
 
I also tried the RblQuery example with the same results.

begin 600 Rbl_0626083833.out.gz
M.:/RMM"*4CN[NU.15\=G03WDF4*.BHEV5%HD2OLB' FH+CBV(-PR4QVT"MP\
MVPFGAZD36$4P8="F!+_A.Z%=;26-$'%3_OI1*>%O6"A-<VWLYM=(U^:-LPSO
ME694,Q2_V'9#XS.HDP;'?G\I:&.G:"/T;_ 6LW@89&BB>.@NB0"C&9C^9/"0
MT_4G4ZIW[T=?5__-W9U]HA=1PJ 5!7ZXF!J41!Q^Z-NMYWE!; W.-'LJP@NK
M89R,T\AYXAC'V*$<]I1'V21@5>F,LJ[)5KA)LD4-%1U$%>/*(BQ^3R%O2W=_
M#?UMN=RLTE'4O^/ECK2>4U"6$!"%O<SB<M%U20/)PZ3&W6C 3\LRUS+] Z+<
M'0EU2*S*3]?I?+*.MJJB/29KD!N0T2!&1 9U^%M> 7N(&&6KDC[RIM4>;'!9
=;&L3#5$$T@'LZBQI2^^+NQ <R#>@/ 2<@Z;E8>X 
 
end

**Comment by eguidotti** [comment]
Thank you for the update. The file seems to be **encrypted**. From the docs:

_With SFTP via the Internet, there is no need for additional payload/content encryption. Clients are discouraged from using legacy DES software encryption option. Existing clients still using DES encryption can contact Customer Support to have DES payload/content encryption removed from their account._

Can you check with Bloomberg Support if this is your case? 
If for any reason removing encryption is not feasible for you, another option would be having the package supporting encrypted files. In order to do that, you can share this GitHub issue with Bloomberg Support so that they can contact me and helping in improving the package.
